from django.db import models


class Tag(models.Model):
    '''Тег для рецепта'''
    name = ...
    color = ...
    slug = ...


class MeasurementUnit(models.Model):
    '''Единица измерения ингридиента'''
    name = ...


class Ingridient(models.Model):
    '''Ингридиент в рецепте'''
    name = ...
    measurement_unit = ...
    amount = ...


class Recipe(models.Model):
    '''Рецепт блюда'''
    author = ...
    name = ...
    image = ...
    text = ...
    ingridients = ...
    tags = ...
    cooking_time = ...
