version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: alexsnik/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ./data:/data
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: alexsnik/foodgram-frontend
    volumes:
      - static_value:/app/result_build/build/static
      - frontend:/app/result_build/build/
    depends_on:
      - backend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/static/
      - media_value:/var/html/media/
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
      - frontend:/usr/share/nginx/html/
    depends_on:
      - backend
      - certbot
volumes:
  static_value:
  media_value:
  frontend: