from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    role = ...
    username = ...
    email = ...
    name = ...
    surname = ...
    favorites = ...
    shopping_cart = ...


class Follow(models.Model):
    author = ...
    subscriber = ...
